insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (1, 'Misti Langley', 'mlangley0@behance.net', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (2, 'Ambros Woolmer', 'awoolmer1@mapy.cz', '151 369 0355');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (3, 'Atalanta Suter', 'asuter2@archive.org', '190 947 3628');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (4, 'Lorette Langforth', 'llangforth3@umn.edu', '953 173 7783');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (5, 'Cathyleen Ros', 'cros4@imageshack.us', '327 897 0484');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (6, 'Erinna Skillicorn', 'eskillicorn5@alibaba.com', '371 451 0394');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (7, 'Jackqueline Renshall', 'jrenshall6@lulu.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (8, 'Terrie Parmiter', 'tparmiter7@nbcnews.com', '883 824 4866');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (9, 'Cary Garbar', 'cgarbar8@spotify.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (10, 'Sherwood Kibbe', 'skibbe9@uiuc.edu', '509 392 1470');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (11, 'Reinwald Quiddinton', 'rquiddintona@seattletimes.com', '235 484 6028');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (12, 'Liva Huffer', 'lhufferb@typepad.com', '255 616 6057');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (13, 'Nate Mindenhall', 'nmindenhallc@bloomberg.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (14, 'Marion Giuroni', 'mgiuronid@harvard.edu', '998 930 8587');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (15, 'Gard Enterle', 'genterlee@privacy.gov.au', '959 605 5518');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (16, 'Dickie Toulch', 'dtoulchf@miibeian.gov.cn', '715 888 9860');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (17, 'Florian Repp', 'freppg@vkontakte.ru', '501 524 2933');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (18, 'Conroy Dannel', 'cdannelh@army.mil', '427 171 0661');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (19, 'Lowrance Sallis', 'lsallisi@wsj.com', '392 235 3573');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (20, 'Dagny Lambillion', 'dlambillionj@spotify.com', '178 290 3339');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (21, 'Bill MacKeogh', 'bmackeoghk@sakura.ne.jp', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (22, 'Pattin Ivanin', 'pivaninl@icio.us', '705 524 9475');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (23, 'Tades Mecchi', 'tmecchim@mapy.cz', '437 317 6150');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (24, 'Wade Linne', 'wlinnen@cloudflare.com', '477 114 9945');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (25, 'Vida Spinks', 'vspinkso@histats.com', '843 598 8424');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (26, 'Blakelee Solland', 'bsollandp@woothemes.com', '752 488 1164');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (27, 'Alleen Guillot', 'aguillotq@yahoo.co.jp', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (28, 'Eileen Hartshorne', 'ehartshorner@timesonline.co.uk', '770 538 4818');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (29, 'Celle Skrzynski', 'cskrzynskis@columbia.edu', '614 242 4002');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (30, 'Con Gatland', 'cgatlandt@oracle.com', '624 647 6052');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (31, 'Deina Barrus', 'dbarrusu@edublogs.org', '622 888 2459');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (32, 'Koenraad Towson', 'ktowsonv@yolasite.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (33, 'Lynne Parks', 'lparksw@multiply.com', '386 357 0511');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (34, 'Rachelle Dibling', 'rdiblingx@mail.ru', '890 624 1791');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (35, 'Theresa Wraxall', 'twraxally@scientificamerican.com', '110 275 0106');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (36, 'Valerie Ockleshaw', 'vockleshawz@live.com', '435 988 8102');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (37, 'Aloisia Robel', 'arobel10@livejournal.com', '147 880 3741');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (38, 'Bili Tolmie', 'btolmie11@hostgator.com', '408 204 3795');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (39, 'Michael Bricket', 'mbricket12@myspace.com', '448 718 7471');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (40, 'Myrtice Goodlett', 'mgoodlett13@twitter.com', '579 368 3164');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (41, 'Melisandra Mallock', 'mmallock14@reference.com', '549 335 9123');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (42, 'Merralee Farran', 'mfarran15@plala.or.jp', '889 155 6268');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (43, 'Aleda Furness', 'afurness16@devhub.com', '223 760 4742');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (44, 'Vikki Gawthorp', 'vgawthorp17@sphinn.com', '236 427 5027');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (45, 'Stanley Biffen', 'sbiffen18@prweb.com', '236 608 6498');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (46, 'Delora Frankom', 'dfrankom19@reuters.com', '948 952 1725');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (47, 'Janaya Strutton', 'jstrutton1a@ebay.com', '755 410 4922');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (48, 'Lorene Cardero', 'lcardero1b@utexas.edu', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (49, 'Lion McQueen', 'lmcqueen1c@auda.org.au', '114 695 5507');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (50, 'Marjie Roz', 'mroz1d@ustream.tv', '848 158 3103');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (51, 'Mallorie Shuttlewood', 'mshuttlewood1e@jalbum.net', '210 975 0228');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (52, 'Herve Mawtus', 'hmawtus1f@newyorker.com', '360 564 8349');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (53, 'Cleveland Spikings', 'cspikings1g@bbc.co.uk', '387 416 6749');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (54, 'Kyle Craigie', 'kcraigie1h@wsj.com', '856 927 9555');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (55, 'Merwyn Wildes', 'mwildes1i@wix.com', '404 335 4797');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (56, 'Rriocard Wilce', 'rwilce1j@wiley.com', '826 526 6022');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (57, 'Coral Seth', 'cseth1k@zdnet.com', '887 155 9256');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (58, 'Carter Sambrook', 'csambrook1l@icq.com', '535 921 1030');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (59, 'Herminia Ludewig', 'hludewig1m@reverbnation.com', '677 463 8045');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (60, 'Kelley Muldoon', 'kmuldoon1n@purevolume.com', '403 193 0274');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (61, 'Ardelia Burkill', 'aburkill1o@nationalgeographic.com', '481 749 0742');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (62, 'Glynis Veal', 'gveal1p@prweb.com', '217 955 9871');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (63, 'Elita de Courcy', 'ede1q@comcast.net', '633 895 4926');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (64, 'Nikita Brosetti', 'nbrosetti1r@newsvine.com', '705 222 3877');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (65, 'Laryssa Muschette', 'lmuschette1s@squarespace.com', '658 696 6337');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (66, 'Lian Tombling', 'ltombling1t@chronoengine.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (67, 'Carter Pickthall', 'cpickthall1u@friendfeed.com', '883 422 1879');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (68, 'Hakeem Goude', 'hgoude1v@senate.gov', '662 723 5942');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (69, 'Udall Poll', 'upoll1w@columbia.edu', '654 258 5207');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (70, 'Carolin Eglise', 'ceglise1x@themeforest.net', '174 150 9370');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (71, 'Jewel Heliar', 'jheliar1y@shop-pro.jp', '121 892 0113');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (72, 'Ned Joly', 'njoly1z@china.com.cn', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (73, 'Petra Faughey', 'pfaughey20@foxnews.com', '572 552 1581');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (74, 'Llewellyn Falk', 'lfalk21@free.fr', '373 429 8491');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (75, 'Lotte Gert', 'lgert22@sciencedaily.com', '915 982 5276');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (76, 'Jilli Itzakovitz', 'jitzakovitz23@wp.com', '670 807 7031');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (77, 'Neda Bentjens', 'nbentjens24@jugem.jp', '500 350 6937');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (78, 'Rodrigo Ison', 'rison25@nih.gov', '188 279 4596');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (79, 'Timmy Doutch', 'tdoutch26@businessweek.com', '953 684 3610');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (80, 'Woodman Monkton', 'wmonkton27@github.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (81, 'Dane Civitillo', 'dcivitillo28@1688.com', '574 305 6462');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (82, 'Stanford Dunston', 'sdunston29@smugmug.com', '910 800 6601');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (83, 'Bank Sibley', 'bsibley2a@myspace.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (84, 'Alika Pilch', 'apilch2b@pcworld.com', '881 236 5397');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (85, 'Tallie Kiossel', 'tkiossel2c@tripadvisor.com', '562 442 4312');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (86, 'Valery Pavkovic', 'vpavkovic2d@dion.ne.jp', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (87, 'Alphard Shadfourth', 'ashadfourth2e@unicef.org', '521 642 1511');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (88, 'Kliment Sorrill', 'ksorrill2f@disqus.com', '236 559 3178');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (89, 'Mimi Thonger', 'mthonger2g@edublogs.org', '358 873 9677');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (90, 'Mace Camblin', 'mcamblin2h@upenn.edu', '150 882 0210');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (91, 'Sharla Catonnet', 'scatonnet2i@amazon.com', '645 512 7672');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (92, 'Wes Hinze', 'whinze2j@geocities.com', '721 538 9832');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (93, 'Nance Hutchin', 'nhutchin2k@state.gov', '256 219 0104');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (94, 'Kath Restall', 'krestall2l@disqus.com', '535 151 0153');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (95, 'Clarice Scamwell', 'cscamwell2m@comcast.net', '129 874 9726');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (96, 'Violante Lawley', 'vlawley2n@shop-pro.jp', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (97, 'Stanleigh Markham', 'smarkham2o@twitpic.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (98, 'Mendie McManamon', 'mmcmanamon2p@elpais.com', '140 855 0510');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (99, 'Dietrich Grugerr', 'dgrugerr2q@pbs.org', '165 701 9509');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (100, 'Farris Jermy', 'fjermy2r@desdev.cn', '559 243 3200');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (101, 'Ingaberg Auguste', 'iauguste2s@exblog.jp', '767 564 1006');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (102, 'Michal Gonnely', 'mgonnely2t@wunderground.com', '857 526 2848');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (103, 'Glori Josum', 'gjosum2u@github.com', '390 698 4695');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (104, 'Shamus Yegorkov', 'syegorkov2v@examiner.com', '474 468 8399');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (105, 'Dalton Tranter', 'dtranter2w@gov.uk', '156 594 8073');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (106, 'Dedie Larver', 'dlarver2x@angelfire.com', '225 812 3429');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (107, 'Brooks Hancock', 'bhancock2y@google.com', '188 872 1470');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (108, 'Clyve Ibanez', 'cibanez2z@google.es', '801 567 1209');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (109, 'Roseanna Gheorghescu', 'rgheorghescu30@wufoo.com', '938 163 5217');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (110, 'Harriot Lydster', 'hlydster31@rediff.com', '860 184 4656');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (111, 'Rodger Skilton', 'rskilton32@unesco.org', '902 954 1176');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (112, 'Clarissa Dovington', 'cdovington33@stumbleupon.com', '632 511 2283');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (113, 'Falito Pigny', 'fpigny34@spiegel.de', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (114, 'Sven Clubley', 'sclubley35@unc.edu', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (115, 'Amalea Castello', 'acastello36@indiegogo.com', '828 580 0793');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (116, 'Nelly Calcraft', 'ncalcraft37@posterous.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (117, 'Heindrick Roarty', 'hroarty38@biblegateway.com', '421 545 3887');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (118, 'Noelyn Pele', 'npele39@google.com', '576 398 5094');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (119, 'Yardley Killiner', 'ykilliner3a@usnews.com', '755 693 4258');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (120, 'Tandi Rubanenko', 'trubanenko3b@altervista.org', '342 140 4811');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (121, 'Clayton Romei', 'cromei3c@i2i.jp', '239 544 5724');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (122, 'Ethelbert Ellar', 'eellar3d@nasa.gov', '325 875 0539');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (123, 'Nessi Snap', 'nsnap3e@reddit.com', '590 424 6469');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (124, 'Faunie Riep', 'friep3f@whitehouse.gov', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (125, 'Stacey Felkin', 'sfelkin3g@state.tx.us', '278 217 7092');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (126, 'Dannel Coogan', 'dcoogan3h@google.de', '751 566 9340');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (127, 'Liz Inglese', 'linglese3i@mapquest.com', '789 950 5836');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (128, 'Garrick Etchingham', 'getchingham3j@yelp.com', '336 421 4676');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (129, 'Jackqueline Palfrie', 'jpalfrie3k@tiny.cc', '182 606 5175');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (130, 'Ansell Stickel', 'astickel3l@pbs.org', '459 359 6920');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (131, 'Seline Warne', 'swarne3m@who.int', '301 683 0481');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (132, 'Aurthur Gwilt', 'agwilt3n@nhs.uk', '181 192 3353');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (133, 'Gwen Chevin', 'gchevin3o@va.gov', '549 549 4967');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (134, 'Sherwin Fey', 'sfey3p@msu.edu', '481 167 1819');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (135, 'Averell Wileman', 'awileman3q@independent.co.uk', '492 546 5050');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (136, 'Peggy Livingston', 'plivingston3r@furl.net', '406 551 9257');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (137, 'Lois Hills', 'lhills3s@purevolume.com', '835 236 0596');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (138, 'Jeannine Redan', 'jredan3t@moonfruit.com', '698 993 6692');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (139, 'Johann MacCahey', 'jmaccahey3u@vkontakte.ru', '718 819 9272');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (140, 'Dell Kondratenya', 'dkondratenya3v@europa.eu', '437 341 9944');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (141, 'Farris Maddaford', 'fmaddaford3w@imageshack.us', '856 784 7001');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (142, 'Kerrill Worgan', 'kworgan3x@blinklist.com', '394 713 4809');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (143, 'Eward O''Cullinane', 'eocullinane3y@prnewswire.com', '102 846 9244');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (144, 'Cherise Hinkes', 'chinkes3z@dagondesign.com', '363 489 8488');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (145, 'Teodoor Tucker', 'ttucker40@about.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (146, 'Magnum Lyford', 'mlyford41@free.fr', '573 290 3580');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (147, 'Reggis Liverock', 'rliverock42@gravatar.com', '431 337 8838');
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (148, 'Mitch Tasker', 'mtasker43@stumbleupon.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (149, 'Clarine Weed', 'cweed44@nationalgeographic.com', null);
insert into natacademy.clientes (id_cliente, nombre, email, telefono) values (150, 'Allyce Kupker', 'akupker45@ucsd.edu', '542 471 6141');