insert into natacademy.productos (id_producto, nombre_producto, precio) values (1, 'Wanton Wrap', 655);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (2, 'Tart - Raisin And Pecan', 541);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (3, 'Wine - Touraine Azay - Le - Rideau', 386);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (4, 'Soup Campbells Mexicali Tortilla', 798);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (5, 'Coriander - Ground', 911);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (6, 'Beans - Navy, Dry', 810);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (7, 'Puree - Passion Fruit', 476);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (8, 'Bread - Focaccia Quarter', 173);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (9, 'Bamboo Shoots - Sliced', 908);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (10, 'Beer - Guiness', 778);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (11, 'Puff Pastry - Slab', 827);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (12, 'Cheese - Boursin, Garlic / Herbs', 866);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (13, 'Shrimp - 16 - 20 Cooked, Peeled', 533);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (14, 'Soup Campbells Split Pea And Ham', 446);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (15, 'Syrup - Golden, Lyles', 822);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (16, 'Chocolate - Semi Sweet', 866);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (17, 'Mustard - Pommery', 470);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (18, 'Pastry - Baked Scones - Mini', 382);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (19, 'Longos - Chicken Caeser Salad', 724);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (20, 'Salt - Celery', 509);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (21, 'Hinge W Undercut', 382);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (22, 'Hinge W Undercut', 868);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (23, 'Hold Up Tool Storage Rack', 817);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (24, 'Beef Cheek Fresh', 601);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (25, 'Tomatoes - Cherry, Yellow', 336);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (26, 'Island Oasis - Raspberry', 936);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (27, 'Hog / Sausage Casing - Pork', 567);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (28, 'Tea - Mint', 848);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (29, 'Chicken Giblets', 453);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (30, 'Brandy Apricot', 245);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (31, 'Tea - Herbal - 6 Asst', 497);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (32, 'Soup - Knorr, Chicken Gumbo', 257);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (33, 'Beef - Kobe Striploin', 430);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (34, 'Pepper - Pablano', 804);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (35, 'Vaccum Bag 10x13', 266);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (36, 'Lamb - Bones', 966);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (37, 'Greens Mustard', 630);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (38, 'Soup - Campbells', 228);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (39, 'Instant Coffee', 943);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (40, 'Waffle Stix', 851);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (41, 'Pasta - Detalini, White, Fresh', 621);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (42, 'Table Cloth 54x54 White', 229);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (43, 'Strawberries', 742);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (44, 'Snapple - Iced Tea Peach', 659);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (45, 'Cheese - Brie Roitelet', 367);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (46, 'Cheese - Swiss Sliced', 746);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (47, 'Raisin - Golden', 578);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (48, 'Breakfast Quesadillas', 985);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (49, 'Lady Fingers', 193);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (50, 'Remy Red', 350);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (51, 'Wine - Pinot Noir Latour', 410);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (52, 'Pineapple - Canned, Rings', 392);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (53, 'Anchovy Paste - 56 G Tube', 222);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (54, 'Madeira', 610);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (55, 'Pastry - Banana Tea Loaf', 380);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (56, 'Sesame Seed', 559);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (57, 'Fruit Mix - Light', 845);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (58, 'Crab - Claws, Snow 16 - 24', 612);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (59, 'Tea - English Breakfast', 380);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (60, 'Rabbit - Whole', 995);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (61, 'Sauce - Ranch Dressing', 119);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (62, 'Frangelico', 688);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (63, 'Ginger - Fresh', 252);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (64, 'Potato - Sweet', 661);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (65, 'Ham - Black Forest', 606);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (66, 'Tofu - Firm', 447);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (67, 'Sauce Tomato Pouch', 857);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (68, 'Bay Leaf', 200);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (69, 'Bulgar', 581);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (70, 'Heavy Duty Dust Pan', 445);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (71, 'Steel Wool', 245);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (72, 'Crab - Imitation Flakes', 107);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (73, 'Beef - Top Sirloin - Aaa', 663);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (74, 'Pork - Bacon, Double Smoked', 724);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (75, 'Yogurt - Plain', 558);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (76, 'Tortillas - Flour, 12', 870);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (77, 'Pears - Fiorelle', 954);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (78, 'Duck - Breast', 633);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (79, 'Jello - Assorted', 165);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (80, 'Mcguinness - Blue Curacao', 777);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (81, 'Cheese - Gouda', 736);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (82, 'Pastry - Apple Muffins - Mini', 732);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (83, 'Calaloo', 923);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (84, 'Olives - Green, Pitted', 347);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (85, 'Peas Snow', 881);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (86, 'Bread - Raisin Walnut Pull', 155);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (87, 'Flour - Cake', 959);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (88, 'Apron', 311);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (89, 'Irish Cream - Baileys', 733);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (90, 'Pomello', 425);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (91, 'Rabbit - Whole', 951);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (92, 'Sour Puss Raspberry', 976);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (93, 'Soupcontfoam16oz 116con', 999);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (94, 'Grapefruit - Pink', 381);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (95, 'Foam Espresso Cup Plain White', 513);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (96, 'Ham - Black Forest', 585);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (97, 'Bar Mix - Lemon', 275);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (98, 'Wine - Penfolds Koonuga Hill', 317);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (99, 'Capicola - Hot', 736);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (100, 'Ginger - Fresh', 968);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (101, 'Scallops - In Shell', 730);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (102, 'Maple Syrup', 464);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (103, 'Wine - White, Pinot Grigio', 209);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (104, 'Glaze - Apricot', 659);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (105, 'Long Island Ice Tea', 421);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (106, 'Tomatoes - Cherry, Yellow', 589);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (107, 'Carbonated Water - White Grape', 605);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (108, 'Vegetable - Base', 322);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (109, 'Horseradish Root', 263);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (110, 'Bacardi Breezer - Tropical', 126);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (111, 'Chips - Doritos', 382);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (112, 'Table Cloth 81x81 White', 936);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (113, 'Turnip - White, Organic', 683);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (114, 'Ice Cream Bar - Drumstick', 275);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (115, 'Foam Tray S2', 116);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (116, 'Pepper - Pablano', 618);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (117, 'Trueblue - Blueberry', 100);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (118, 'Pickerel - Fillets', 324);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (119, 'Trueblue - Blueberry 12x473ml', 488);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (120, 'Jack Daniels', 159);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (121, 'Marsala - Sperone, Fine, D.o.c.', 837);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (122, 'Lid - 16 Oz And 32 Oz', 759);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (123, 'Bread - Corn Muffaletta', 781);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (124, 'Dry Ice', 172);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (125, 'Beef - Rouladin, Sliced', 334);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (126, 'Mushroom - Enoki, Dry', 107);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (127, 'Pepper - Black, Crushed', 306);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (128, 'Nut - Almond, Blanched, Ground', 636);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (129, 'Soap - Hand Soap', 594);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (130, 'Pork - Loin, Boneless', 224);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (131, 'Chocolate - Feathers', 575);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (132, 'Oil - Truffle, White', 106);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (133, 'Bread - Roll, Italian', 965);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (134, 'Oneshot Automatic Soap System', 211);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (135, 'Wine - Tio Pepe Sherry Fino', 823);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (136, 'Chick Peas - Dried', 978);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (137, 'Basil - Seedlings Cookstown', 633);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (138, 'Butter Ripple - Phillips', 719);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (139, 'Dill - Primerba, Paste', 691);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (140, 'Jam - Marmalade, Orange', 360);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (141, 'Teriyaki Sauce', 560);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (142, 'Butter - Unsalted', 754);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (143, 'Oil - Pumpkinseed', 944);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (144, 'Eggroll', 399);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (145, 'Dried Apple', 600);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (146, 'Fond - Neutral', 454);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (147, 'Chocolate - Chips Compound', 387);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (148, 'Steam Pan - Half Size Deep', 222);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (149, 'Pastry - Chocolate Marble Tea', 515);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (150, 'Pepper - White, Ground', 106);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (151, 'Muffin Mix - Banana Nut', 743);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (152, 'Sherry - Dry', 993);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (153, 'Soup - Campbells, Beef Barley', 334);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (154, 'Chicken - Base, Ultimate', 355);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (155, 'Cup - Paper 10oz 92959', 945);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (156, 'Quail - Jumbo Boneless', 738);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (157, 'Melon - Honey Dew', 105);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (158, 'True - Vue Containers', 336);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (159, 'Sproutsmustard Cress', 228);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (160, 'Cheese - Grana Padano', 613);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (161, 'Cheese - Pont Couvert', 999);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (162, 'Beef Wellington', 295);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (163, 'Turnip - White', 482);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (164, 'Crab - Dungeness, Whole', 179);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (165, 'Taro Root', 783);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (166, 'Cup - Paper 10oz 92959', 876);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (167, 'Worcestershire Sauce', 878);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (168, 'Rice Pilaf, Dry,package', 872);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (169, 'Tart Shells - Barquettes, Savory', 987);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (170, 'Thyme - Fresh', 964);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (171, 'Tomatoes - Grape', 421);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (172, 'Bouq All Italian - Primerba', 949);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (173, 'Milkettes - 2%', 130);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (174, 'Island Oasis - Peach Daiquiri', 919);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (175, 'Pepper - Cayenne', 900);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (176, 'Wine - Magnotta - Cab Sauv', 735);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (177, 'Wine - Bouchard La Vignee Pinot', 568);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (178, 'Appetizer - Tarragon Chicken', 409);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (179, 'Octopus - Baby, Cleaned', 586);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (180, 'Pie Filling - Pumpkin', 931);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (181, 'Sage Derby', 457);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (182, 'Pastry - Apple Large', 550);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (183, 'Beans - Black Bean, Preserved', 688);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (184, 'Schnappes Peppermint - Walker', 991);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (185, 'Tuna - Yellowfin', 145);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (186, 'Scrubbie - Scotchbrite Hand Pad', 392);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (187, 'Juice - Clamato, 341 Ml', 179);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (188, 'Island Oasis - Ice Cream Mix', 827);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (189, 'Wine - Beringer Founders Estate', 423);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (190, 'Gelatine Leaves - Bulk', 749);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (191, 'Potatoes - Idaho 100 Count', 148);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (192, 'Steam Pan - Half Size Deep', 843);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (193, 'Assorted Desserts', 146);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (194, 'Pasta - Lasagna, Dry', 273);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (195, 'Pepper - Paprika, Spanish', 108);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (196, 'Ecolab - Hobart Washarm End Cap', 963);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (197, 'Stock - Beef, White', 196);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (198, 'Wine - Magnotta - Cab Franc', 337);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (199, 'Crab - Back Fin Meat, Canned', 207);
insert into natacademy.productos (id_producto, nombre_producto, precio) values (200, 'Wine - Pinot Grigio Collavini', 810);
